name: "nest"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nest.api
    env_file: ".env"
    networks:
      - nestnetwork
    depends_on:
      - nest.db
      - nest.redis
    restart: on-failure
    ports:
      - 8080:8080

  nest.db:
    image: postgres:16-alpine
    container_name: nest.db
    restart: always
    networks:
      - nestnetwork
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest.redis:
    image: "redis:alpine"
    container_name: nest.redis
    restart: always
    networks:
      - nestnetwork
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
  redis-data:

networks:
  nestnetwork:
